version: '3.8'

services:
  backend:
    build: ./backend
    container_name: smartinventory_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=smartinventory
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: smartinventory_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    stdin_open: true
    tty: true

  db:
    image: postgres:15-alpine
    container_name: smartinventory_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smartinventory
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
