"""add_group_description

Revision ID: bd3a16a3992e
Revises: 49458ec8acdd
Create Date: 2025-12-31 20:47:12.014622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd3a16a3992e'
down_revision: Union[str, None] = '49458ec8acdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventorygroup', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True))
    op.alter_column('item', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('sharedaccess', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user', 'auth_provider',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'EMAIL'::character varying"))
    op.alter_column('user', 'force_password_change',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'force_password_change',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('user', 'auth_provider',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'EMAIL'::character varying"))
    op.alter_column('sharedaccess', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('item', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_column('inventorygroup', 'description')
    # ### end Alembic commands ###
