"""Add settings and meta_data

Revision ID: fc3a13642d0c
Revises: 574feb197d78
Create Date: 2026-01-11 19:00:26.301199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fc3a13642d0c'
down_revision: Union[str, None] = '574feb197d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventorygroup', sa.Column('settings', sa.JSON(), nullable=True))
    op.add_column('item', sa.Column('meta_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'meta_data')
    op.drop_column('inventorygroup', 'settings')
    # ### end Alembic commands ###
