"""add_currency_to_groups

Revision ID: 574feb197d78
Revises: b622e5b11a74
Create Date: 2026-01-01 00:46:54.425408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '574feb197d78'
down_revision: Union[str, None] = 'b622e5b11a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('inventorygroup', sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE inventorygroup SET currency = 'USD'")
    op.alter_column('inventorygroup', 'currency', nullable=False, server_default='USD')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventorygroup', 'currency')
    # ### end Alembic commands ###
